// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Blender","status":true,"description":"Enhane Roll Playing Game.","parameters":{}},
{"name":"SRD_UltraBase","status":true,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"SRD_HUDMakerUltra","status":true,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"false","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"125","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}},
{"name":"SRD_MapEdgeTrigger","status":true,"description":"Allows for events to be triggered when pushing the map's edge.","parameters":{}}
];
