// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SimpleMsgSideViewMZ","status":true,"description":"At sideview battle, only display item/skill names.","parameters":{"displayAttack":"false","displayIcon":"true"}},
{"name":"AltMenuScreen2MZ","status":true,"description":"Yet another menu screen layout","parameters":{"allowWindowDisp":"true","maxColsMenu":"2","commandRows":"1","commandCols":"7","isDisplayStatus":"true","display map name":"true","location string":"Location:","bgBitmapMenu":"","doesNotSetItemScene":"true","bgBitmapItem":"","doesNotSetSkillScene":"true","bgBitmapSkill":"","doesNotSetEquipScene":"true","bgBitmapEquip":"","doesNotSetStatusScene":"true","bgBitmapStatus":"","doesNotSetOptionScene":"true","bgBitmapOptions":"","doesNotSetSaveScene":"true","bgBitmapFile":"","doesNotSetEndScene":"true","bgBitmapGameEnd":""}},
{"name":"MZYUNoMakeSmalBattleUiPLZ","status":true,"description":"","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"Kaliya_ActorBattlePosition","status":true,"description":"Actor Battle Positions","parameters":{}}
];
